# Generated by Django 2.2.4 on 2021-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='creature',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
