# Generated by Django 2.2 on 2019-08-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='source',
            field=models.CharField(default='Great Quail', max_length=64),
        ),
    ]
