# Generated by Django 2.2 on 2019-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_creature_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='player',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
