# Generated by Django 2.2.4 on 2021-01-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_creature_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='nickname',
        ),
    ]
