# Generated by Django 3.2 on 2021-05-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_collectornybnkindreds_collectorranygarous'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='territory',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='creature',
            name='weakness',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
