# Generated by Django 2.2 on 2019-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20190815_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='concept',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='creature',
            name='condition',
            field=models.CharField(blank=True, default='-OK-', max_length=4),
        ),
        migrations.AlterField(
            model_name='creature',
            name='demeanor',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='creature',
            name='faction',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='creature',
            name='group',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='creature',
            name='groupspec',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='creature',
            name='nature',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='creature',
            name='path',
            field=models.CharField(default='Humanity', max_length=64),
        ),
        migrations.AlterField(
            model_name='creature',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='creature',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='creature',
            name='sire',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='creature',
            name='source',
            field=models.CharField(blank=True, default='Great Quail', max_length=64),
        ),
        migrations.AlterField(
            model_name='creature',
            name='topic',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
