# Generated by Django 2.2.4 on 2021-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_remove_creature_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
