# Generated by Django 3.2 on 2021-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20210518_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('name', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('chronicle_acronym', models.CharField(blank=True, default='', max_length=16)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('era', models.CharField(blank=True, default='2019', max_length=16)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
