# Generated by Django 2.2 on 2019-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20190815_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='condition',
            field=models.CharField(blank=True, default='OK', max_length=32),
        ),
    ]
