# Generated by Django 3.2 on 2021-05-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
