# Generated by Django 2.2 on 2019-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20190818_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='time_in_torpor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
