# Generated by Django 2.2 on 2019-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_creature_time_in_torpor'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='discipline_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='expected_freebies',
            field=models.IntegerField(default=0),
        ),
    ]
