# Generated by Django 2.2 on 2019-08-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20190818_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='discipline_points',
            new_name='disciplinepoints',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='expected_freebies',
            new_name='expectedfreebies',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='time_in_torpor',
            new_name='timeintorpor',
        ),
    ]
