# Generated by Django 2.2 on 2019-08-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20190818_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='finaldeath',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='nickname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
