# Generated by Django 2.2 on 2019-08-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20190820_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
