# Generated by Django 2.2.4 on 2021-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20210410_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='need_fix',
            field=models.BooleanField(default=False),
        ),
    ]
