# Generated by Django 2.2 on 2019-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20190820_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='ghost',
            field=models.BooleanField(default=False),
        ),
    ]
