# Generated by Django 2.2.4 on 2019-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_creature_ghost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('acronym', models.CharField(blank=True, default='', max_length=16)),
                ('main_creature', models.CharField(blank=True, default='', max_length=128)),
                ('image_logo', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
