# Generated by Django 2.2.4 on 2021-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20210410_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='freebies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
