# Generated by Django 2.2.4 on 2019-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_chronicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='era',
            field=models.IntegerField(default=2019),
        ),
    ]
