# Generated by Django 2.2.4 on 2021-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_creature_freebies'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
