# Generated by Django 2.2.4 on 2019-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_chronicle_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
