# Generated by Django 2.2.4 on 2021-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_creature_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='total_backgrounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_gifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_knowledges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_mental',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_physical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_skills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_social',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_talents',
            field=models.IntegerField(default=0),
        ),
    ]
