# Generated by Django 2.2.4 on 2021-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_auto_20210107_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='primogen',
            field=models.BooleanField(default=False),
        ),
    ]
