# Generated by Django 2.2.4 on 2021-01-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_creature_primogen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['name'], 'verbose_name': 'Creature'},
        ),
    ]
