# Generated by Django 2.2.4 on 2021-01-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_auto_20210109_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='domitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Domitor', to='collector.Creature'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='source',
            field=models.CharField(blank=True, default='zaffarelli', max_length=64),
        ),
    ]
