# Generated by Django 2.2.4 on 2021-04-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_auto_20210421_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='extra',
            field=models.IntegerField(default=0),
        ),
    ]
