# Generated by Django 2.2.4 on 2021-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_creature_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('level', models.PositiveIntegerField(default=0)),
                ('breed_0', models.BooleanField(default=False, verbose_name='Homid')),
                ('breed_1', models.BooleanField(default=False, verbose_name='Metis')),
                ('breed_2', models.BooleanField(default=False, verbose_name='Lupus')),
                ('aupice_0', models.BooleanField(default=False, verbose_name='Ragabash')),
                ('aupice_1', models.BooleanField(default=False, verbose_name='Theurge')),
                ('aupice_2', models.BooleanField(default=False, verbose_name='Philodox')),
                ('aupice_3', models.BooleanField(default=False, verbose_name='Galliard')),
                ('aupice_4', models.BooleanField(default=False, verbose_name='Ahroun')),
                ('tribe_0', models.BooleanField(default=False, verbose_name='Black Furies')),
                ('tribe_1', models.BooleanField(default=False, verbose_name='Black Spiral Dancers')),
                ('tribe_2', models.BooleanField(default=False, verbose_name='Bone Gnawers')),
                ('tribe_4', models.BooleanField(default=False, verbose_name='Children of Gaia')),
                ('tribe_6', models.BooleanField(default=False, verbose_name='Fiannas')),
                ('tribe_7', models.BooleanField(default=False, verbose_name='Glass Walkers')),
                ('tribe_8', models.BooleanField(default=False, verbose_name='Gets of Fenris')),
                ('tribe_9', models.BooleanField(default=False, verbose_name='Red Talons')),
                ('tribe_10', models.BooleanField(default=False, verbose_name='Silent Striders')),
                ('tribe_11', models.BooleanField(default=False, verbose_name='Silver Fangs')),
                ('tribe_12', models.BooleanField(default=False, verbose_name='Stargazers')),
                ('tribe_13', models.BooleanField(default=False, verbose_name='Uktenas')),
                ('tribe_14', models.BooleanField(default=False, verbose_name='Wendigos')),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
