# Generated by Django 2.2.4 on 2021-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='declaration',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
