# Generated by Django 2.2.4 on 2021-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_auto_20210425_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='auspices',
            field=models.CharField(default='.....', max_length=5),
        ),
        migrations.AddField(
            model_name='gift',
            name='breeds',
            field=models.CharField(default='...', max_length=3),
        ),
    ]
