# Generated by Django 2.2.4 on 2021-04-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_auto_20210425_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='alternative_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
