# Generated by Django 2.2.4 on 2021-04-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_gift_alternative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='tribe_15',
            field=models.BooleanField(default=False, verbose_name='White Howlers'),
        ),
        migrations.AddField(
            model_name='gift',
            name='tribe_3',
            field=models.BooleanField(default=False, verbose_name='Bunyips'),
        ),
        migrations.AddField(
            model_name='gift',
            name='tribe_5',
            field=models.BooleanField(default=False, verbose_name='Croatans'),
        ),
        migrations.AddField(
            model_name='gift',
            name='tribes',
            field=models.CharField(default='________________', max_length=16),
        ),
    ]
