# Generated by Django 2.2.4 on 2021-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_creature_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='patron',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
