# Generated by Django 2.2.4 on 2021-04-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_creature_merit4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='merit4',
        ),
    ]
