# Generated by Django 2.2.4 on 2021-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0037_auto_20210427_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='flaw4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='merit4',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creature',
            name='new_domitor',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
