# Generated by Django 2.2.4 on 2021-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_auto_20210427_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='new_domitor',
        ),
        migrations.AlterField(
            model_name='creature',
            name='domitor',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
