# Generated by Django 3.2 on 2021-05-29 03:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0006_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('dday', models.DateTimeField(default=datetime.datetime.now, verbose_name='D-Day')),
                ('is_current', models.BooleanField(default=False)),
                ('chronicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.chronicle')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('time_offset_hours', models.IntegerField(blank=True, default=-1)),
                ('time_offset_custom', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('era', models.CharField(blank=True, default='2019', max_length=16)),
                ('is_current', models.BooleanField(default=False)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storytelling.place')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storytelling.story')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storytelling.story'),
        ),
    ]
