# Generated by Django 3.2 on 2021-05-29 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='dday',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fuD-Day'),
        ),
    ]
