# Generated by Django 3.2 on 2021-05-29 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0004_alter_story_dday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='dday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
