# Generated by Django 3.2 on 2021-05-31 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0005_alter_story_dday'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
