# Generated by Django 3.2 on 2021-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0007_place_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='place_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
