# Generated by Django 3.2 on 2021-06-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0008_scene_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='importance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
