# Generated by Django 3.2 on 2021-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0009_place_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='era',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='is_current',
        ),
    ]
