# Generated by Django 3.2 on 2021-06-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0010_auto_20210604_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOE', 'Enemies action consequences'), ('FRIEND', 'Allies action consequences'), ('THIRD', 'Third Party action consequences'), ('TIME', 'Time passing consequences'), ('FATE', 'Randomness, luck, fate consequences')], default='', max_length=10)),
                ('scene_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_from', to='storytelling.scene')),
                ('scene_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scene_to', to='storytelling.scene')),
            ],
            options={
                'ordering': ['category', 'scene_from', 'scene_to'],
            },
        ),
    ]
