# Generated by Django 3.2 on 2021-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0011_sceneslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneslink',
            name='category',
            field=models.CharField(choices=[('FOE', 'Enemies action consequences'), ('FRIEND', 'Allies action consequences'), ('THIRD', 'Third Party action consequences'), ('TIME', 'Time passing consequences'), ('FATE', 'Randomness, luck, fate consequences')], default='TIME', max_length=10),
        ),
    ]
