# Generated by Django 3.2 on 2021-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0012_alter_sceneslink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneslink',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
