# Generated by Django 3.2 on 2021-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0013_sceneslink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneslink',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
