# Generated by Django 3.2 on 2021-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0014_sceneslink_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneslink',
            name='order_in',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sceneslink',
            name='order_out',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
