# Generated by Django 3.2 on 2021-06-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0015_auto_20210604_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneslink',
            name='scene_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenefrom', to='storytelling.scene'),
        ),
        migrations.AlterField(
            model_name='sceneslink',
            name='scene_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sceneto', to='storytelling.scene'),
        ),
    ]
