# Generated by Django 3.2 on 2021-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0016_auto_20210604_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
