# Generated by Django 3.2 on 2021-06-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0017_scene_is_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_current',
        ),
    ]
