# Generated by Django 3.2 on 2021-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0019_auto_20210605_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='acronym',
            field=models.CharField(default='', max_length=16),
        ),
    ]
