# Generated by Django 3.2 on 2021-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0020_story_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_downtime',
            field=models.BooleanField(default=False),
        ),
    ]
