# Generated by Django 3.2 on 2021-06-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0021_scene_is_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='special_rules',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
