# Generated by Django 3.2 on 2021-06-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling', '0022_place_special_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='cast',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
